//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Телеком_Нева_СвязьEntities : DbContext
    {
        public Телеком_Нева_СвязьEntities()
            : base("name=Телеком_Нева_СвязьEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Данные_по_оборудованию> Данные_по_оборудованию { get; set; }
        public virtual DbSet<Данные_по_подключению_абонентов> Данные_по_подключению_абонентов { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Тип_оборудования> Тип_оборудования { get; set; }
        public virtual DbSet<Тип_порта> Тип_порта { get; set; }
    }
}
