//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_по_оборудованию
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Данные_по_оборудованию()
        {
            this.Данные_по_подключению_абонентов = new HashSet<Данные_по_подключению_абонентов>();
        }
    
        public int ID_оборудования { get; set; }
        public string Наименование_оборудования { get; set; }
        public Nullable<int> Тип { get; set; }
        public string Серийный_номер { get; set; }
        public string MAC_адрес { get; set; }
        public string IP_адрес { get; set; }
        public string Номер_телефона { get; set; }
        public Nullable<System.DateTime> Дата_установки { get; set; }
    
        public virtual Тип_оборудования Тип_оборудования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_по_подключению_абонентов> Данные_по_подключению_абонентов { get; set; }
    }
}
